spring:
  application:
    name: currency-service

server:
  port: 3000


app:
  variables:
    url: http://cbr.ru/scripts/XML_daily.asp


eureka:
  client:
    enabled: false
    service-url:
      defaultZone: http://localhost:8761/eureka



