eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: currency-service
          uri: http://host.docker.internal:8080
          predicates:
            - Path=/currency/**
        - id: processing-service
          uri: http://host.docker.internal:8085
          predicates:
            - Path=/processing/**

logging:
  level:
    root: DEBUG