server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: currency-service
          uri: http://localhost:3000
          predicates:
            - Path=/currency/**
        - id: processing-service
          uri: http://localhost:3001
          predicates:
            - Path=/processing/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
