spring:
  application:
    name: processing-service

  jpa:
    show-sql: false       # Hibernate SQL можно отключить, будем смотреть через P6Spy
    properties:
      hibernate.format_sql: true
      hibernate.use_sql_comments: true

  datasource:
    url: jdbc:p6spy:postgresql://localhost:5432/processing
    username: java_user
    password: java_password
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

    hikari:
      auto-commit: false
      connection-timeout: 20000
      minimum-idle: 5
      maximum-pool-size: 12
      idle-timeout: 300000
      max-lifetime: 1200000

logging:
  level:
    com.p6spy.engine.spy: DEBUG
    org.springframework.transaction: DEBUG

server:
  port: 3005



service:
  currency:
    url: http://localhost:8080




# flyway:
#   enabled: true
#   locations: classpath:db
#   url: jdbc:postgresql://localhost:5432/processing
#   username: java_user
#   password: java_password


eureka:
  client:
    enabled: false
    service-url:
      defaultZone: http://localhost:8761/eureka

